### ISSUE TITLE
Metal Support

### ISSUE THREAD

**Issue by jordo1138** [mit-han-lab/streaming-llm#18]
`raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

Any plans to get Metal support for us M2 users without CUDA?  Thanks!

**Comment by Guangxuan-Xiao** [comment]
Can you give me your full stack trace? Did you install the correct PyTorch for M2 Mac?

**Comment by jordo1138** [comment]
Sure can give it soon, it's true the default command in your setup environment section of the readme will not give a compiled for CUDA torch because PyTorch requires M1/M2 to compile from source because they know Apple Silicon doesn't support it. Are you suggesting it doesn't need to use CUDA but needs PyTorch to be compiled with it? Like in your run example 
`cuda_visible_devices=0` which implies its off anyhow?

**Comment by jordo1138** [comment]
I think both of the example .py files are importing torch expecting cuda device support.
Perhaps in future I can look into example that would use Metal instead
Thanks
`import torch
from tqdm import tqdm
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
from torch.nn import CrossEntropyLoss
from streaming_llm.kv_cache import StartRecentKVCache
from streaming_llm.utils import parse_args, load

**device = "cuda"**
`

**Comment by jordo1138** [comment]
oh good news I fixed it, in the 
File "examples/run_streaming_llama.py", line 67, in streaming_inference
need to change from "cuda" to "mps" for metal performance shaders

Working now thanks. I"ll make a PR & readme later for Metal Support.

**Comment by jordo1138** [comment]
leaving this in-case other M2 users come by to check for support. Modify the .py example from "cuda" -> "mps" 
<img width="606" alt="streamingllm example changed from cuda to mps support" src="https://github.com/mit-han-lab/streaming-llm/assets/8525512/bfb183c1-7972-48b6-8b41-b895890a328c">

**Comment by tomaarsen** [comment]
You can use `input_ids.to(model.device)` to make it work regardless of whether you have mps, cuda or even something else.

**Comment by jordo1138** [comment]
That was my first try :) in this case I got a failure from torch expecting
an explicit type. Will share the error when choosing device.
